2023-03-13 22:37:20 â€” INFO â€” Running with edr=0.7.5
2023-03-13 22:37:20 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
2023-03-13 22:37:23 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_latest_invocation", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:37:25 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_latest_invocation", "macro_args": {}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:37:25  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:37:25  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}[0m
2023-03-13 22:37:25 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_elementary_database_and_schema", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:37:27 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2023-03-13 22:37:27 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:37:30 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:37:29  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:37:29  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}
Please reach out to our community for help with this issue.[0m
NoneType: None
2023-03-13 22:42:30 â€” INFO â€” Running with edr=0.7.5
2023-03-13 22:42:30 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
2023-03-13 22:42:33 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_latest_invocation", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:42:35 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_latest_invocation", "macro_args": {}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:42:35  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:42:35  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}[0m
2023-03-13 22:42:35 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_elementary_database_and_schema", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:42:37 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2023-03-13 22:42:37 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:42:39 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:42:39  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:42:39  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}
Please reach out to our community for help with this issue.[0m
NoneType: None
2023-03-13 22:43:20 â€” INFO â€” Running with edr=0.7.5
2023-03-13 22:43:20 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
2023-03-13 22:43:22 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_latest_invocation", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:43:25 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_latest_invocation", "macro_args": {}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:43:24  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:43:24  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}[0m
2023-03-13 22:43:25 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_elementary_database_and_schema", "macro_args": {}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:43:27 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2023-03-13 22:43:27 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}} --project-dir /usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project
[31;20m2023-03-13 22:43:29 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command - {'returncode': 2, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "metrics_sample_limit": 5, "disable_passed_test_metrics": false}}', '--project-dir', '/usr/local/lib/python3.11/site-packages/elementary/monitor/dbt_project'], 'output': b"22:43:29  Encountered an error while reading the project:  ERROR: Runtime Error\n  Could not find profile named 'elementary'\n22:43:29  Encountered an error:\nRuntime Error\n  Could not run dbt\n", 'stderr': b''}
Please reach out to our community for help with this issue.[0m
NoneType: None
